let suggestions = [
    "Angular vs React",
    "Action",
    "Best Coding language",
    "Blogger",
    "Bollywood",
    "Channel",
    "CSS3",
    "cricket",
    "Coding is easy",
    "Designer",
    "Dart",
    "Developer",
    "easycoding",
    "easycoding youtube channel",
    "Freelancer",
    "facebok page",
    "Flutter",
    "Youtube",
    "Youtube channel",
    "Web designer",
    "Web developer",
    "Login form in HTML & CSS",
    "How to learn HTML & CSS",
    "How to  become Freelancer",
    "What does Html Stands for",
    "What does CSS stands for",
    
]